version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - not_null
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one per row per products_id found in each orders_id.
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            tests:
              - not_null
              - unique
      - name: ship
        identifier: raw_gz_ship
        description: shipping details of greenweez
        columns:
          - name: orders_id
            description: order id
            tests:
              - not_null
              - unique
      - name: adwords
        identifier: raw_gz_adwords
        description: greenweez's adwords
        tests:
          - unique:
              column_name: "(date_date || '_' || paid_source || '_' || campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        description: greenweez's bing
        tests:
          - unique:
              column_name: "(date_date || '_' || paid_source || '_' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        description: greenweez's criteo
        tests:
          - unique:
              column_name: "(date_date || '_' || paid_source || '_' || campaign_key)"
      - name: facebook
        identifier: raw_gz_facebook
        description: greenweez's facebook
        tests:
          - unique:
              column_name: "(date_date || '_' || paid_source || '_' || campaign_key)"